### ISSUE TITLE
Overflow icon ripple color not adjustable

### ISSUE THREAD

**Issue by Guuz** [vonovak/react-navigation-header-buttons#104]
The header buttons support changing of the ripple/press color on Android using a prop. But the Overflow Button (https://github.com/vonovak/react-navigation-header-buttons/blob/master/src/overflowMenu/OverflowMenu.js) does not.

This way you get inconsistent ripple colors in the app.

**Comment by vonovak** [comment]
hello, I will accept a PR that fixes this, thank you!
