### ISSUE TITLE
OverflowIcon prop is not optional (on Android)

### ISSUE THREAD

**Issue by willlma** [vonovak/react-navigation-header-buttons#11]
According to the README, `HeaderButtons`_will render android-styled overflow icon by default_ if no `OverflowIcon` is provided, but in my experience no icon is rendered on Android if it is left out.

Conversely, [the example](https://github.com/vonovak/react-navigation-header-buttons/blob/master/example/navbar-buttons-demo/screens/UsageWithOverflow.js#L31) explicitly includes an `OverflowIcon`. When I use this, the overflow icon is rendered correctly, but `IconComponent` and `IconSize` props become unnecessary. 

**The code I thought would work:**
```
import HeaderButtons, { Item } from 'react-navigation-header-buttons';
import Icon from 'react-native-vector-icons/Ionicons';

<HeaderButtons
  IconComponent={Icon}
  iconSize={23}
>
  <Item
    title='Delete'
    show='never'
    onPress={this.deleteSentence}
  />
</HeaderButtons>
```
**The code that ended up working:**
```
<HeaderButtons OverflowIcon={<Icon name={this.moreIcon} size={23} />}>
  <Item
    title='Delete'
    show='never'
    onPress={this.deleteSentence}
  />
</HeaderButtons>
```

**Comment by vonovak** [comment]
hi @willlma thanks for reporting, the behavior changed slightly for 1.0.0, the OverflowIcon is now required if you need overflow buttons. No default is provided.
