### ISSUE TITLE
Add numbers in cart icon

### ISSUE THREAD

**Issue by rishabh72** [vonovak/react-navigation-header-buttons#111]
In my e-commerce app I added cart icon in my header using this package. I want to show numbers above cart icon. How to show numbers above icon?

**Comment by vonovak** [comment]
hello, this package does not do any magic with the visible components you render, so just render the cart with the number just like you would render it anywhere else. Take a look at this example: 

https://github.com/vonovak/react-navigation-header-buttons/blob/master/example/screens/UsageCustom.tsx

hope this helps, thank you!
