### ISSUE TITLE
Typescript Error

### ISSUE THREAD

**Issue by Keplyx** [vonovak/react-navigation-header-buttons#113]
when running tsc on my project using typescript 4.1.3 and react-navigation-header-buttons 6.2.0, I get this error:

```
node_modules/react-navigation-header-buttons/index.d.ts:109:14 - error TS7051: Parameter has a name but no type. Did you mean 'arg0: OnOverflowMenuPressParams'?

109   onPress?: (OnOverflowMenuPressParams) => any;
```

And here is the class throwing the error:
![Screenshot_20210207_115828](https://user-images.githubusercontent.com/23726131/107144500-cbe98d80-693b-11eb-9d18-4772bb4da410.png)

I only see this error when running the tsc check, so it doesn't show while coding, but makes the tsc command exit with code 1, so I cannot use it in my build process.

**Comment by vonovak** [comment]
hello, thanks for reporting. I will accept a PR with a fix, thank you.
