### ISSUE TITLE
navigation.setParams invalidate the ripple effect of the buttons

### ISSUE THREAD

**Issue by tong233** [vonovak/react-navigation-header-buttons#12]
here my code.
```
static navigationOptions = ({ navigation }) => {
    const params = navigation.state.params || {}
    return {
      headerTitle: 'Title',
      headerRight: (
        <HeaderButtons color="white">
          <HeaderButtons.Item
            title={params.listMode ? 'list' : 'node'}
            onPress={params.switchMode}
            buttonStyle={{ fontSize: 17 }}
          />
        </HeaderButtons>
      )
    }
  }

 state = {
    listMode: false
  }
  componentDidMount() {
    this.props.navigation.setParams({
      listMode: this.state.listMode,
      switchMode: () => {
        const listMode = !this.state.listMode
        this.setState({ listMode })
        this.props.navigation.setParams({ listMode }) // remove This line ripple does work.
      }
    })
  }
```
use  TouchableNativeFeedback component instead of HeaderButtons work well

**Comment by vonovak** [comment]
hi @tong233! As mentioned in the readme (albeit the readme is a little inaccurate), the button won't react to touches if the onPress prop is a falsy value, as can be seen [here](https://github.com/vonovak/react-navigation-header-buttons/blob/4c714b29c5819c65241809d6abf83d4b69c31aae/src/HeaderButton.js#L19) can you put a console.warn in there and see what is being passed into the component?

**Comment by tong233** [comment]
@vonovak 
Is it Touchable?
![image](https://user-images.githubusercontent.com/21073132/41152937-d1bdcbb2-6b47-11e8-9dd1-5ad41732fb87.png)
