### ISSUE TITLE
Not working in web browser

### ISSUE THREAD

**Issue by mleister97** [vonovak/react-navigation-header-buttons#123]
Hi, the component `ReactNavigationHeaderButton` is not working in webbrowser. (It does work on my android device).

Is it possible to also support the button in web view?

Getting the following issue:

```
TypeError: react_native_web_dist_exports_TouchableNativeFeedback__WEBPACK_IMPORTED_MODULE_4__.default.Ripple is not a function
```

![image](https://user-images.githubusercontent.com/16700053/113171650-f4a94780-9247-11eb-958c-e7a4fc98a695.png)

**Comment by vonovak** [comment]
Hello and thanks for reporting! I am sorry for the bug, this probably broke when I was refactoring touchables.

Unfortunately, I do not have time to maintain web support so I will not be able to fix this ant time soon, but I will welcome and merge a PR that fixes this issue. Thank you!🙂

**Comment by mleister97** [comment]
Hi, a easy fix will look like this:

TouchableItem.js:30
```js
  const background = React.useMemo(() => {
    if (Platform.OS === 'android' && Platform.Version >= ANDROID_VERSION_LOLLIPOP) {
      return TouchableNativeFeedback.Ripple(pressColor, borderless, rippleRadius);
    }
    return null;
  }, [pressColor, borderless, rippleRadius]);
```

**Comment by mleister97** [comment]
Looks like useMemo is called regardless of the platform which will lead to the issue.
The fix is working properly

**Comment by vonovak** [comment]
@mleister97 sounds good! Do you want to submit a PR or should I fix it?

**Comment by mleister97** [comment]
Wow, so quick responses :D 
Feel free to fix it :D
