### ISSUE TITLE
How to pass TouchableProps in <Item />

### ISSUE THREAD

**Issue by Stophface** [vonovak/react-navigation-header-buttons#128]
How do I pass `TouchableProps` like `disabled` through the `<Item />` component?

```
<Item
        onPress={() => foo(avatar)}
        title='Save'
        TouchableProps={{ disabled: isEqual(what, ever) }} />
```

This is not how it works.

**Comment by vonovak** [comment]
hello, please take a look here: https://github.com/vonovak/react-navigation-header-buttons/blob/master/example/screens/UsageDisabled.tsx

**Comment by Stophface** [comment]
@vonovak 
Unfortunatly that is not answering my Question. How do I pass `TouchableProps` through?

**Comment by vonovak** [comment]
hello again, I'm sorry but I do not know what you are looking for. You asked how to pass eg. `disabled` prop and the link answers the question. There is no such thing as `TouchableProps` that you could pass and I don't know what that should do anyway...? 
If you rephrase your question then I can answer but right now I don't know what you're after 🙂  Thanks :)

**Comment by vonovak** [comment]
hello, maybe this clarifies the question https://github.com/vonovak/react-navigation-header-buttons/pull/129/files

**Comment by Stophface** [comment]
Aaah, okay. I thought with `Touchable Props` I can pass props to the underlying `Touchable` -> `Touchable Opacity` from `RN`.
