### ISSUE TITLE
OverflowMenu wrong onPress callback called

### ISSUE THREAD

**Issue by mmaass** [vonovak/react-navigation-header-buttons#140]
Hi,

i have two **HiddenItems** in an **OverflowMenu**. The 1st item is disabled. When i click on the second item, the onPress callback of the first (disabled one) gets called.

I've captured a video of the bug.

https://user-images.githubusercontent.com/576477/125589410-c05d7b0e-a58e-47f9-9274-9bc4f9857de8.mp4

Or am I doing something wrong here? I've also tried not to define the **onPress** prop on the first item, but this causes an error as well. (which is at least consistent with the aforementioned bug)

The version is 7.0.1

**Comment by vonovak** [comment]
hello, please find 

https://github.com/vonovak/react-navigation-header-buttons/blob/2fca2fd21020af0590a6c60d938b17848cfb1e13/src/overflowMenuPressHandlers.js#L89

and change 

`hiddenButtons[buttonIndex - 1].onPress();`

to

`enabledButtons[buttonIndex - 1].onPress();`

and let me know if it works, thanks!

**Comment by mmaass** [comment]
Yes, that fixes the problem.

**Comment by vonovak** [comment]
that bug managed to live there for a pretty long time... thanks for reporting!

**Comment by mmaass** [comment]
thanks for fixing
