### ISSUE TITLE
ios icons appears as md icons

### ISSUE THREAD

**Issue by EKOLX** [vonovak/react-navigation-header-buttons#144]
Hi,

`import React from "react";
import { HeaderButton } from "react-navigation-header-buttons";
import { Ionicons } from "@expo/vector-icons";

const IoniconsHeaderButton = (props: any) => {
  return <HeaderButton IconComponent={Ionicons} iconSize={23} {...props} />;
};

export default IoniconsHeaderButton;`

I use **ios-arrow-back** icon.

`<HeaderButtons HeaderButtonComponent={IoniconsHeaderButton}>
                <Item
                  title="Back"
                  iconName="ios-arrow-back"
                  color="#000"
                  onPress={() => {}}
                />
              </HeaderButtons>`

Icons resource: [https://infinitered.github.io/ionicons-version-3-search/](url)

<img width="1104" alt="Screen Shot 2021-07-23 at 16 58 59" src="https://user-images.githubusercontent.com/24255958/126784994-d68f6c68-bb95-4abd-b86b-226fbc7c5cf6.png">

as you can see from screenshot icon appears differently

<img width="356" alt="Screen Shot 2021-07-23 at 16 56 43" src="https://user-images.githubusercontent.com/24255958/126784769-307beedd-06b9-46ff-8323-71a6984cd4d8.png">

**Comment by vonovak** [comment]
Hello, this library takes no control over how the icons are rendered, so the issue is not here.

Since you're using expo vector icons, I suggest you use this directory: https://icons.expo.fyi/

Thanks you!
