### ISSUE TITLE
findNodeHandle warning in strict mode

### ISSUE THREAD

**Issue by yangm97** [vonovak/react-navigation-header-buttons#158]
```
ExceptionsManager.js:184 Warning: findNodeHandle is deprecated in StrictMode. findNodeHandle was passed an instance of BaseButton which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://reactjs.org/link/strict-mode-find-node
```

Annoying but seems to be harmless.

**Comment by vonovak** [comment]
Hello and thanks for reporting,

`UIManager.showPopupMenu` requires that we pass the id obtained via `findNodeHandle` so there's no way around this. Maybe `UIManager.showPopupMenu` will be updated or removed from RN core, we'll see. Either way, there's nothing to do about the warning for the time being.


Thank you 🙂
