### ISSUE TITLE
Rendering text-only HeaderButton throws an error

### ISSUE THREAD

**Issue by francisbrito** [vonovak/react-navigation-header-buttons#17]
![screenshot_1529593977](https://user-images.githubusercontent.com/2180822/41728195-2cb95ba2-7544-11e8-84ca-eb669fd0054a.png)

The culprit seems to be this line: https://github.com/vonovak/react-navigation-header-buttons/blob/master/src/HeaderButtons.js#L11

Adding `const IS_IOS = Platform.OS === 'ios'` before L10 should fix it.

I can make a PR for this, if you're OK with it :)

**Comment by vonovak** [comment]
whoa, how did I miss this? Sure, the constant is defined in Overflow button, please export it from there, thanks.
