### ISSUE TITLE
File is typescript but extension is `.js`

### ISSUE THREAD

**Issue by trajano** [vonovak/react-navigation-header-buttons#190]
Related https://github.com/typescript-eslint/typescript-eslint/issues/6362

When I added the package I get the following error in the linter.

```
❯ yarn lint
yarn run v1.22.19
$ eslint "**/*.{ts,tsx}"

Error while parsing C:\p\spring-docker\node_modules\react-navigation-header-buttons\src\overflowMenu\OverflowMenuContext.js
Line 24, column 78: ';' expected.
`parseForESLint` from parser `C:\p\spring-docker\packages\eslint-config\node_modules\@typescript-eslint\parser\dist\index.js` is invalid and will just be ignored
```

Looking at the file, it looks like it is a TypeScript file not a javascript but the filename extension is `.js`

**Comment by trajano** [comment]
Just did a bit of research on [flow](https://flow.org/) since that is what appears to be used.  I think all that's needed is [flow-remove-types](https://flow.org/en/docs/tools/flow-remove-types/) to be added in the prepublish phase and change the main to use the removed types file.  That way it will be treated as a normal JS file

**Comment by trajano** [comment]
It seems to be tied with the import linter because of the eslint-plugin-import.  I guess if I switch to prettier-plugin-orgainze-imports it will skip seeing error at least.

**Comment by vonovak** [comment]
Hello and thanks for reporting,
it feels a little odd that you'd lint code that lives in your node_modules, no? Each dependency can be built with different eslint config and so many dependencies may not be in line with your rules. To me it sounds like you should lint only your sources. Does that help?
Thank you 🙂
