### ISSUE TITLE
Left button margins do not match value for right aligned buttons.

### ISSUE THREAD

**Issue by webdevmario** [vonovak/react-navigation-header-buttons#206]
I upgraded from v10.0.0 to v11.0.0, set the new provider with a stack type of "js" per my react navigation settings and noticed that the margins for right side buttons is significantly larger than that of left side buttons. This is fine on v10.0.0. Was this intentional?

https://github.com/vonovak/react-navigation-header-buttons/blob/master/src/ButtonsWrapper.tsx

**Comment by vonovak** [comment]
Hello and thanks for asking,
I believe it was, if you think it looks odd, can you share a screenshot?
Thank you 🙂

**Comment by DreamGamer** [comment]
Same issue here on Android and IOS:
![signal-2023-10-18-030231_002](https://github.com/vonovak/react-navigation-header-buttons/assets/15878146/ad0743ec-dfe8-46d5-9ff7-9aa969bf721d)
