### ISSUE TITLE
renderButton is a required prop

### ISSUE THREAD

**Issue by sarahsporck** [vonovak/react-navigation-header-buttons#207]
It seems, that the `renderButton` prop in the `HeaderButton` is mandatory in the current version of this package. It would be nice if you could either update the example in the README.md or if you could make the property optional.

**Comment by vonovak** [comment]
Hello and thanks for asking,
please let me know if this PR helps, https://github.com/vonovak/react-navigation-header-buttons/pull/208

if not, I'll need an example of what you're trying to achieve. The `renderButton` prop is required, but a default value for the prop is provided by the library, so you should not need to specify your own.
Thank you 🙂

**Comment by sarahsporck** [comment]
Ah! Thanks. This works perfectly. Also if anyone else also has a different setup than in the example, you can also import and pass the default renderButton method :)

**Comment by vonovak** [comment]
yes, an example of how that can be customized is actually in the example app https://github.com/vonovak/react-navigation-header-buttons/blob/master/example/src/components/MaterialHeaderButton.tsx
