### ISSUE TITLE
React native Header Button  icons show up as a crossed out boxes on Android

### ISSUE THREAD

**Issue by donaldCull** [vonovak/react-navigation-header-buttons#26]
`"dependencies": {
    "react": "16.4.1",
    "react-native": "0.55.4",
    "react-native-vector-icons": "^5.0.0",
    "react-navigation": "^2.11.2",
    "react-navigation-header-buttons": "2.1.0"
  },`

I'm running react native inside an android emulator.  I have previously used react-navigation header buttons when using Expo and have displayed the icons successfully.   However using this same method only renders crossed out boxes in android.

Is there a reason why the icons do not render in Android?

Thanks

![screenshot_1533881370](https://user-images.githubusercontent.com/20510711/43941655-4c3c84cc-9cb8-11e8-96a9-ed9ec392dccb.png)

**Comment by vonovak** [comment]
closing since it seems resolved
