### ISSUE TITLE
Can't find variable: Ionicons using the example code.

### ISSUE THREAD

**Issue by Benzer1406** [vonovak/react-navigation-header-buttons#3]
I copied the example code of the presentation page of react-navigation-header-buttons but I get the error "Can't find variable: Ionicons". I imported everything, but the error still is there.

**Comment by vonovak** [comment]
Hi! Sorry, but I cannot help without a reproduction of the issue. Have you installed all required packages?

**Comment by Benzer1406** [comment]
Yes I did, I switched back to `react-native-vector-icons`, so don't worry. But now I have the issue that if I add more than 2 icons the second icon is a "?" even though I added the same icon with no difference...

**Comment by vonovak** [comment]
you probably do not have the icons module linked correctly

**Comment by Benzer1406** [comment]
Any advice what I can do to avoid that my headerButtons are all so close together? I tried `marginRight`, `marginLeft`, `margin`, but nothing worked.

**Comment by vonovak** [comment]
please try https://github.com/vonovak/react-navigation-header-buttons/blob/master/example/navbar-buttons-demo/screens/UsageCustom.js#L15

**Comment by Benzer1406** [comment]
Great, that's it. Didn't notice that I had to put the props inside the buttonWrapperStyle. Thank you!

**Comment by vonovak** [comment]
@Benzer1406 kindly close the issue if the questions were answered
