### ISSUE TITLE
Overflow button shows up with animation but hides immediately. 

### ISSUE THREAD

**Issue by kolyneh** [vonovak/react-navigation-header-buttons#32]
Overflow button shows up with animation but hides immediately.  
Can we control if to enable animation?

**Comment by vonovak** [comment]
hi! can you clarify what you mean? I'm not sure I understand.

**Comment by kolyneh** [comment]
Hi !
I'm using like this codes on `TabNavigator` with 2 tabs `Tab1` and `Tab2`, `Tab1` has headerRight buttons , `Tab2` does not.

### Tab1 Screen:
```` 
headerRight: (
                 <HeaderButtons OverflowIcon={<Image source={i_add} resizeMode='contain'/>}
                                overflowButtonWrapperStyle={{marginRight: 12, padding: 4}}
                 >
                     <HeaderButtons.Item
                         show='never'
                         title='A'
                     />
                     <HeaderButtons.Item
                         show='never'
                         title='B'
                     />
                 </HeaderButtons>
             ),
````
When switch from `Tab2` to `Tab1`, the `Overflow button` shows up with slow animation;
When switch from `Tab1` to `Tab2`, the `Overflow button` hides without animation.

Is it clear?
Can I control if to show `Overflow button` with animation?

**Comment by vonovak** [comment]
@kolyneh having a gif or an example on https://snack.expo.io/ would help, but that being said, this package does not handle animation stuff, the animation comes from somewhere else.

**Comment by kolyneh** [comment]
@vonovak Hi, 
I found it was a problem on `Image`, fixed by adding prop `fadeDuration={0}` to `Image` .
 snack here: [https://snack.expo.io/@kolyneh/issue-on-overflow-button](url)

**Comment by kolyneh** [comment]
@vonovak 
This problem is only on Android. May be `fadeDuration` of `Image` is not with default value `0` on Android.
