### ISSUE TITLE
how can i change 'cancel' button text  to '取消' 

### ISSUE THREAD

**Issue by daniel031699** [vonovak/react-navigation-header-buttons#36]
the button ‘cancel’  text cant change

**Comment by vonovak** [comment]
hi! get inspired here https://github.com/vonovak/react-navigation-header-buttons/blob/fc5b31f47cbd17f6252f150940ea73a4064fa11c/src/OverflowButton.js#L81 and use the onOverflowMenuPress prop:

`onOverflowMenuPress?: ({ hiddenButtons: Array<React.Element<*>>, overflowButtonRef: ?View }) => any` prop
