### ISSUE TITLE
replicate react-navigation back button TouchableOpacity

### ISSUE THREAD

**Issue by gbminnock** [vonovak/react-navigation-header-buttons#38]
Hi, 
I would like to replicate the circular and sort of black-ish background TouchableOpacity that is used to react-navigation. 

Currently using your library the background shows up as a square - is it possible to back this circular? 
My code goes like this: 

```javascript 
<HeaderButton
    {...passMeFurther}
    IconComponent={Icon}
    iconSize={32}
    color="white"
    background={Touchable.Ripple("black")}
  />
```
and later in my navigation options:
````javascript
<HeaderButtons HeaderButtonComponent={IoniconsHeaderButton}>
        <Item
          title="share"
          iconName="md-share"
          onPress={() => alert("share")}
        />
````
Tks

**Comment by vonovak** [comment]
yes, see example https://github.com/vonovak/react-navigation-header-buttons/blob/master/example/navbar-buttons-demo/screens/UsageCustomRipple.js

to make your square round, you need to use `Touchable.Ripple("black", true)`
