### ISSUE TITLE
display icon before title

### ISSUE THREAD

**Issue by prasan2421** [vonovak/react-navigation-header-buttons#40]
is it possible to display icon and title together? 
i need to display both icon and name together but cannot find a way to do it.
eg:
<Item title="search" iconName="ios-search" onPress={() => alert('search')} />

so i need to display :  (search icon) search

**Comment by vonovak** [comment]
hi! you'll need to use the `ButtonElement` prop.

**Comment by arantessergio** [comment]
Hi! Is it possible render custom lines in the overflow menu using the ButtonElement prop?

**Comment by vonovak** [comment]
@arantessergio I'm not sure what you mean by custom lines, why don't you try out? :)

**Comment by arantessergio** [comment]
@vonovak , Sorry, I did not express myself very well. But, I mean something like that:

```
<View style={{ flexDirection: 'row }}>
    <Icon />
    <Text />
</View>
```

To show an icon and a text in the Items with `show='never'` prop.

**Comment by vonovak** [comment]
> show an icon and a text in the Items with `show='never'`

how do you want to show something, if you set `show='never'`? I don't understand. If you want to show those things in the overflow menu, please use the `onOverflowMenuPress` prop

**Comment by vonovak** [comment]
closing as resolved
