### ISSUE TITLE
Show menu on header buttons

### ISSUE THREAD

**Issue by ronce96** [vonovak/react-navigation-header-buttons#42]
There is no possibility of adding a popup menu as an Item.
![image](https://user-images.githubusercontent.com/17070304/53944183-1ebaca80-40bf-11e9-98b8-e1168216fda7.png)![image](https://user-images.githubusercontent.com/17070304/53944150-12367200-40bf-11e9-962c-ecd27d3aee41.png)

**Comment by vonovak** [comment]
this is supported. popup menu show for the items that have `show: "never"`

**Comment by Barney4242** [comment]
Thanks a lot for the library!
Is it possible to style this popup menu, e.g. to add right margin like on the image above. The property right in overflowMenuView seems has another effect...

**Comment by vonovak** [comment]
hi @Barney4242 this is currently not possible. Please use `onOverflowMenuPress` prop and take a look at

https://callstack.github.io/react-native-paper/menu.html

https://github.com/callstack/react-native-paper/tree/master/src/components/Menu
