### ISSUE TITLE
Use native iOS color (light blue) by default

### ISSUE THREAD

**Issue by xaphod** [vonovak/react-navigation-header-buttons#50]
Code:

```
      <HeaderButtons>
        <HeaderButtons.Item
          onPress={() => {
            navigation.state.params.submit();
            navigation.popToTop();
          }}
          title="Submit"
        />
      </HeaderButtons>
```

Expected result: the "Submit" button is the standard iOS native color (light blue in iOS 12).

Actual result: it is black text

**Comment by vonovak** [comment]
hello and thanks for reporting. I expect people to customize the color according to their needs, so I'll close this.
