### ISSUE TITLE
Doesn't work with expo 33

### ISSUE THREAD

**Issue by hadnazzar** [vonovak/react-navigation-header-buttons#51]
I updated the version of expo to 33.0.0 and my header buttons disappeared. Was working with version 32.0.0 

Now it just shows back button in from default navigation.

**Comment by vonovak** [comment]
hi! Do you have a repro on snack? I'm just working on v3 of this lib, using expo 33 and it works just fine. Without a repro, I'll have to close this, thanks.

**Comment by vonovak** [comment]
hi again, I'm closing this because the example app uses expo 33 and works just fine.
