### ISSUE TITLE
Broken readme example

### ISSUE THREAD

**Issue by MitchK** [vonovak/react-navigation-header-buttons#53]
```
export { Item } from 'react-navigation-header-buttons';
```
results in
```
'react-navigation-header-buttons' has no exported member 'Item'
```
using version 3.0.1

**Comment by vonovak** [comment]
hi! Sorry for having the problem. I cannot reproduce the issue, can you repro it on https://snack.expo.io ? Thanks

**Comment by AliYar-Khan** [comment]
I am trying to create a button on the header of the navigation header of react-navigation. But i have failed to do so. Using the example at the react navigation and also this library examples. Any. My component where i want to add the button on the header has also redux store connected. So keep in mind that as well !

**Comment by vonovak** [comment]
the readme is updated, so the example should be fine
