### ISSUE TITLE
Ripple effect not working on Android with Icon in Headerbutton

### ISSUE THREAD

**Issue by mleister97** [vonovak/react-navigation-header-buttons#61]
I faced the same issue as Aashish Sapkota.
Stackoverflow Link: https://stackoverflow.com/questions/60066251/fading-animation-not-working-on-header-icon-react-native

On IOS the effect is working fine, but on Android the "ripple" effect is missing.

**Comment by vonovak** [comment]
hi, yes, I'm aware of this, it's probably android version-dependent. I'll try to publish a fix soon.

**Comment by ashishspkota14** [comment]
Thank you. I am looking forward to this issue to be fixed.

**Comment by vonovak** [comment]
can you please confirm this is fixed in 3.0.5?
