### ISSUE TITLE
How to show both title and text?

### ISSUE THREAD

**Issue by renanBritz** [vonovak/react-navigation-header-buttons#64]
Hi.

I'm trying to use a button in headerLeft. The expected behavior would be to show the icon and the title, just like react navigation does. Example: "< Back". But the component shows either the text or the icon, regardless of the available space in the header.

Any suggestions?

**Comment by vonovak** [comment]
hello, this use isn't really covered by the library. It shows either text or icon. If you want to customize the back title, see the views in https://github.com/react-navigation/react-navigation/tree/master/packages/stack/src/views/Header - you can import them and override what you need.

**Comment by renanBritz** [comment]
Could you allow that behavior? I believe its valid. Btw, the README has an example with icon and title at the same time, so I thought it was possible.

When I navigate to a different stack, React Navigation doesnt create the Back button, so I was trying to add it manually. I know this is a React Navigation issue but maybe I'm doing it wrong?

Thanks!

**Comment by vonovak** [comment]
title and icon will not be rendered at the same time because it's an unusual use case, but you can use custom elements as documented in the readme. In v4 (see PR), rendering custom elements will be more straightforward.
