### ISSUE TITLE
How can I disable the button? Like on iOS .isEnabled = false

### ISSUE THREAD

**Issue by app-arianamini** [vonovak/react-navigation-header-buttons#68]
I don't mean hide and show the button, I wand enable or disable the header button icon based on my conditions.

**Comment by vonovak** [comment]
hello, currently, this is done by no passing an `onPress` handler. You can also try passing `disabled` prop, might work too. see https://github.com/vonovak/react-navigation-header-buttons/blob/master/example/screens/UsageDisabled.tsx
