### ISSUE TITLE
React Navigation Version 5.x

### ISSUE THREAD

**Issue by gibo77** [vonovak/react-navigation-header-buttons#69]
Does this one compatible for React Navigation Version 5.x?
I just want to make sure before installing.
Thanks for your API.

**Comment by vonovak** [comment]
hello, I believe it does, but if you want to install the next version of the library I recommend you install from this PR https://github.com/vonovak/react-navigation-header-buttons/pull/67

it's missing documentation but all the examples in the `example` folder are updated so you can get inspired there. I'm planning to release this in the next ~2 weeks or so. I just need to update the docs and some styling, but the api will very likely stay as it is.

**Comment by Iamthereality** [comment]
> Does this one compatible for React Navigation Version 5.x?
> I just want to make sure before installing.
> Thanks for your API.

Just tested React Navigation version 5.x with latest available via npm release of react-navigation-header-buttons and everything works fine.
