### ISSUE TITLE
Any way this might be able to support react-native-web?

### ISSUE THREAD

**Issue by cmaycumber** [vonovak/react-navigation-header-buttons#70]
I'm running into an issue with ActionSheetIOS when trying to compile to RNW. 

Do you think it would be possible to support this? I imagine it would require switching to something like @expo/react-native-action-sheet and I'm not sure that falls into the scope of the library.

**Comment by cmaycumber** [comment]
This was due to the fact that the versions of react-native-web > 12 remove items that are no longer supported in the react-native core. I think this should work with RNW versions <= 11.x.

**Comment by vonovak** [comment]
Please note that you can pass custom onPress listener for the overflow menu. Also check out the PR for version 4 - the library is rewritten from a fair part. There is no documentation for version 4 yet, but the examples are updated and you can get inspired there.
