### ISSUE TITLE
Overriding IconComponent in Item does not seem to work

### ISSUE THREAD

**Issue by DomiR** [vonovak/react-navigation-header-buttons#73]
In the previous version we were able to pass the icon for each item. We used material and material-community icons, because both sets do not have all icons. 

Now I don't see how we could achieve this? Each Menubuttons has only one Icon "factory".

**Comment by DomiR** [comment]
Sorry about the confusion, I've just realized that `Item` has the `IconComponent` prop, that should probably override the used IconComponent, but for me this is not working. It is still using the `IconComponent` from the `MenuButton` component from the context...

**Comment by vonovak** [comment]
hello and thanks for the comment. Does this not work for you? https://github.com/vonovak/react-navigation-header-buttons/blob/master/example/screens/UsageDifferentFontFamilies.tsx

**Comment by vonovak** [comment]
a full code snippet would help so we're both on the same page

**Comment by DomiR** [comment]
Okay, I messed up 😬 

```js
import Icon from 'react-native-vector-icons/MaterialIcons';

// I used the following snippet, so I did override my passed props...
const MaterialIconHeaderButton = props => (
	<RNHeaderButton {...props} IconComponent={Icon} iconSize={24} />
);

// when I should have used, so passed props actually override IconComponent
const MaterialIconHeaderButton = props => (
	<RNHeaderButton IconComponent={Icon} iconSize={24} {...props}/>
);
```

Thanks for the quick response!
