### ISSUE TITLE
HiddenButton Icon??

### ISSUE THREAD

**Issue by eshraj302** [vonovak/react-navigation-header-buttons#75]
Hey there! thanks for taking the time to creating this library and making my life easier. I want to know how can we add icon to the HiddenItem component inside the Overflow Menu, 
I have linked the example below, how can we achieve the similar result?
I think it would be better if we had more control over the HiddenItem view component
Thanks in Advance!

(https://user-images.githubusercontent.com/55375862/82705753-e38dc280-9c95-11ea-9420-a80e95e54ee6.jpeg)

**Comment by vonovak** [comment]
hello and thanks for asking. This is undocumented (will document) but you can pass an `icon` prop to `HiddenItem`. See https://github.com/vonovak/react-navigation-header-buttons/blob/master/example/screens/UsageWithOverflowComplex.tsx

> I think it would be better if we had more control over the HiddenItem view component

can you please be more specific? What extra control do you want? Thanks!

**Comment by eshraj302** [comment]
Thanks for replying fast, Sorry as i was busy with another Project.  I have already used this example on link :  https://github.com/vonovak/react-navigation-header-buttons/blob/master/example/screens/UsageWithOverflowComplex.tsx
But i want to provide icon in <HiddenItem /> with "overflowMenuPressHandlerPopupMenu" handler as show in the image i shared above, is it possible somehow?

> can you please be more specific? What extra control do you want? Thanks!
I meant, if it could be possible to control the contents of <HiddenItem>, then we could directly pass other components to it

`<HiddenItem>
<Icon name="list" size={25} color="black" />
<View><Text>List Item 1</Text></View>
</HiddentItem>`

Thanks

**Comment by vonovak** [comment]
@eshraj302 yes, what you asked for in the image is possible, just take a look at the link I provided above:

```
<HiddenItem
            icon={<MaterialIcons name="search" size={23} />}
            title="List Item 1"
            onPress={() => alert('search')}
          />
```

 Does that answer the question? If this is not what you want, then I don't understand what you want, please be more specific. Thanks!

**Comment by eshraj302** [comment]
@vonovak the example is great, But what i am asking is <HiddenItem> component neglects the icon prop when used with  "overflowMenuPressHandlerPopupMenu". It doesnt show the icon with the item.
Is there a workaround for that?
If you still don't understand my issue, if you get little free time, Please try to implement the example in image for me. It will very nice of you
With any other handler(onPressOverflowMenu handlers) it works like a charm. 
Thanks!

**Comment by vonovak** [comment]
@eshraj302 hi again, okay, I missed the `overflowMenuPressHandlerPopupMenu` part. 

Having images in `overflowMenuPressHandlerPopupMenu` is not supported and I do not plan to support that - you'd have to implement this directly in React Native or create a custom implementation.

`overflowMenuPressHandlerDropdownMenu` offers more customization options so if you need icons or other stuff, I recommend using that. 

Thank you!
