### ISSUE TITLE
SVG instead of react-native-vector-icons on OverflowMenu

### ISSUE THREAD

**Issue by jayzyaj** [vonovak/react-navigation-header-buttons#80]
Tried to use SVG Icons instead of vector-icons on OverflowMenu and it's not working.

**Comment by vonovak** [comment]
sorry, this is such a vague description that I cannot do anything about it. You can render whatever you want using this library - see https://github.com/vonovak/react-navigation-header-buttons/blob/master/example/screens/UsageCustom.tsx
