### ISSUE TITLE
ActionSheetIOS is missing in react-native-web >= 0.12.0

### ISSUE THREAD

**Issue by chrda81** [vonovak/react-navigation-header-buttons#82]
When using react-native-web package I get the error

`Module not found: Can't resolve 'react-native-web/dist/exports/ActionSheetIOS'`

which points to file  _react-navigation-header-buttons/src/overflowMenuPressHandlers.js_. Since react-native-web package >= version 0.12.0 the export of ActionSheetIOS was removed. Could this be fixed?

**Comment by vonovak** [comment]
hello, on web you can only use `overflowMenuPressHandlerDropdownMenu` (see https://github.com/vonovak/react-navigation-header-buttons#overflowmenu).


regarding removal of ActionSheetIOS from react-native web, nothing can be done about that, you need to provide your own implementation

you can pass your own custom handler, eg. `@expo/react-native-action-sheet` as seen in https://github.com/vonovak/react-navigation-header-buttons/blob/master/example/screens/UsageCustomOverflow.tsx


hope this helps!

**Comment by chrda81** [comment]
> regarding removal of ActionSheetIOS from react-native web, nothing can be done about that, you need to provide your own implementation

I've found the solution for my problem. I forgot to install and configure the babel plugin for react-native-web, so that all imports are correctly rewritten. The wrapper class ActionSheetIOS is not part of react-native-web anymore and is now rewritten by the babel plugin to the original class of react-native.

If someone else runs into that same problem, this link might help: https://github.com/necolas/react-native-web/tree/master/packages/babel-plugin-react-native-web

**Comment by outaTiME** [comment]
Same here guys, any advice or example will be welcome 🙏
