### ISSUE TITLE
Now add png icon

### ISSUE THREAD

**Issue by fobtracker** [vonovak/react-navigation-header-buttons#87]
I have a png icon. Can i add to this package? I use package react-native-vector-icons but i want to add me icon.

**Comment by vonovak** [comment]
hello, yes, you can render whatever you want in the header, see https://github.com/vonovak/react-navigation-header-buttons/blob/master/example/screens/UsageCustom.tsx

**Comment by fobtracker** [comment]
> hello, yes, you can render whatever you want in the header, see https://github.com/vonovak/react-navigation-header-buttons/blob/master/example/screens/UsageCustom.tsx

Thanks for that quick reply.
