### ISSUE TITLE
Optional icon loading

### ISSUE THREAD

**Issue by dotemacs** [vonovak/react-navigation-header-buttons#9]
Hi,

thanks for the library. Just tried it and I like it. 

In the app I'm writing there are no icons in the header, only text. 

So when I tried to use it with just this library installed, I got this error:

```trace
error: bundling failed: Error: Unable to resolve module 
`react-native-vector-icons/MaterialIcons` from 
`....path-to-my-app..../node_modules/react-navigation-header-buttons/OverflowButton.js`: 
Module does not exist in the module map
```

I see that there's a PR pending for this issue: https://github.com/vonovak/react-navigation-header-buttons/pull/8

Figured I'd write here instead of polluting the PR discussion.

**Comment by vonovak** [comment]
hi @dotemacs, can you please try https://github.com/vonovak/react-navigation-header-buttons-base

thanks

**Comment by dotemacs** [comment]
Hi @vonovak 

sorry for the delay in responding back.

Just tried it and it works great :)

Thank you for your work

**Comment by vonovak** [comment]
hi @dotemacs just fyi, I changed the behavior slightly in 1.0.0: `react-navigation-header-buttons` does not depend on vector icons any more, but you're required to provide `OverflowIcon` if you want it. react-navigation-header-buttons-base won't be developer further on.
