### ISSUE TITLE
Wrong OverflowMenu / HiddenItem components anchor position on landscape

### ISSUE THREAD

**Issue by allandiego** [vonovak/react-navigation-header-buttons#99]
Im using this components for header menus and i noticed that the anchor point for landscape screen orientation is wrong even in the expo example, is it the default behavior or bug?

![landscape](https://user-images.githubusercontent.com/6215050/97031706-171b9400-1537-11eb-97ce-8e0f558d33c1.jpeg)

![portrait](https://user-images.githubusercontent.com/6215050/97031710-184cc100-1537-11eb-9542-9b0408ea3048.jpeg)

**Comment by vonovak** [comment]
hi! This is a bug, but I don't know how to reproduce it; can you write your steps to reproduce, or perhaps post a video recording? 
Thanks!

**Comment by allandiego** [comment]
What a crazy bug, I think its a expo or react-navigation thing check this out :
https://youtu.be/ZPuVJO_Fo6

some how my test app is affecting the  react-navigation-header-buttons expo example app too. It was working fine with same code before update to expo 39, no anchor problems you can check this in default release channel.

Demo app
https://expo.io/@vonovak/projects/navbar-buttons-demo

My test app:
https://expo.io/@adcr/cell-counter?release-channel=testing

Things i have noticed:
Preference route that appears not affect the header button have this unmountOnBlur: true option while History Count route dont
```tsx
<Drawer.Screen
        name="PreferenceRoutes"
        component={PreferenceRoutes}
        options={{
          drawerLabel: I18n.t('screens.preference.drawerMenu'),
          unmountOnBlur: true,
          drawerIcon: ({ color }): React.ReactNode => (
            <Icon name="tune" size={30} color={color} />
          ),
        }}
      />
```
The main route when app open have a OrientationChangeEvent listener just to set a state variable and after navigate to the History Count route thats messing things out the listener stops to work as you can see in video
```tsx
  const handleOrientationChange = useCallback(
    async (event: ScreenOrientation.OrientationChangeEvent) => {
      // UNKNOWN = 0, PORTRAIT_UP = 1, PORTRAIT_DOWN = 2,LANDSCAPE_LEFT = 3, LANDSCAPE_RIGHT = 4
      const isLandscape = event.orientationInfo.orientation > 2;
      setIsLandscapeLayout(isLandscape);
      setIsHeaderVisible(!isLandscape);
    },
    []
  );

  useFocusEffect(
    useCallback(() => {
      ScreenOrientation.addOrientationChangeListener(handleOrientationChange);
      activateKeepAwake();

      return () => {
        ScreenOrientation.removeOrientationChangeListeners();
        deactivateKeepAwake();
      };
    }, [handleOrientationChange])
  );
``` 

If you close expo app and run demo exemple again it works correctly

**Comment by allandiego** [comment]
I found the problem, its the AdMobBanner from expo-ads-admob causing the errors on screen orientation listener and the anchor point. The strange part is that it is affecting other expo apps like in video
